---
 - name: My Super Playbook
   hosts: all 
   become: yes

   vars:
     mytext: "Privet from Vlady"

   tasks:
   - name: Ping test
     ping:

   - name: Unregister Server from Load Balancer
     shell: echo This server {{ inventory_hostname }} was deregistered from Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
     delegate_to: 127.0.0.1

   - name: Update my Datebase
     shell: echo  UPDATING Database....
     run_once: true

   - name: Create file1
     copy:
       dest: /home/file1.txt
       content: |
          This is Filen1
          in English Hello World
          on russian {{ mytext }}
     delegate_to: linux1

   - name: Create file2
     copy:
       dest: /home/file2.txt
       content: |
          This is Filen2
          in English Hello World
          on russian {{ mytext }}
     delegate_to: Ubuntu

   - name: Reboot my servers
     shell: sleep 3 && reboot now
     async: 1
     poll: 0


   - name: Wait till my server will come up online
     wait_for:
           host: "{{ inventory_hostname }}"
           state: started
           delay: 5
           timeout: 45
     delegate_to: 127.0.0.1
