---
 - name: Loops Playbook
   hosts: Ubuntu
   become: yes

   tasks:
    - name: Say Hello to All
      debug: msg="Hello {{ item }}"
      loop: 
           - "Vlady"
           - "YERYS"


    - name: Loop untill example
      shell: echo -n Z >> myfile.txt && cat myfile.txt
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find("ZZZZ") == false


    - name: Print Final Output
      debug:
        var: output.stdout

#    - name: Install many packaged
#      yum: name={{ item }} state=installed
#      with_items:
#              - mysql-client
#              - python

