---
 - name: Ansible Lesson 19
   hosts: all
   any_errors_fatal: True
   become: yes


   tasks: 

   - name: Task Number1
     yum: name=treeeee state=latest
     ignore_errors: True

   - name: Task Number2
     shell: echo Hello World!
     register: results
#     failed_when: results.rc ==0
#     failed_when: "`World` in results.stdout"


   - debug:
       var: results

   - name: Task Number 3
     shell: echo Privet Mir!!
